services:
  - type: web
    name: tesslate-app-6
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: sh -c "uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./app.db
      - key: SECRET_KEY
        value: tesslate-secret-6
      - key: ENVIRONMENT
        value: production
